CREATE SCHEMA `SISEG` DEFAULT CHARACTER SET utf8 ;

USE SISEG;

create table PERSONA(
    BOLETA VARCHAR(12) PRIMARY KEY, 
    CORREO VARCHAR(50) UNIQUE,
    CURP VARCHAR(18) UNIQUE,
    CONTRASENA VARCHAR(255), -- MODIFICAR POR EL TIPO DE CIFRADO A UTILIZAR
    NOMBRE VARCHAR(50),
    ROL ENUM('ALUMNO', 'P_ADMIN') NOT NULL, 
    SEXO CHAR(1),
    TELEFONO_MOVIL VARCHAR(10), -- JUNTAR AMBOS TELEFONOS EN UNA COLUMNA ROMPERIA LA NORMALIZACION
    TELEFONO_FIJO VARCHAR(10)
);

CREATE TABLE PLAZA(
    CARRERA INT, -- HOMEOPATA 1, PARTERO 2
    ESTATUS INT, -- INACTIVO 0, ACTIVO 1
	PROMOCION VARCHAR(10), -- EJEMPLO 2025-1
    SECCION VARCHAR(50), 
    SEDE VARCHAR(50) PRIMARY KEY, -- Nombre del hospital
    TARJETA_DISPONIBLE INT,
    TIPO_BECA INT, -- REVISAR DATO
    UBICACION VARCHAR(100) 
);

CREATE TABLE ALUMNO(
	BOLETA VARCHAR(12) PRIMARY KEY,
	CARRERA INT, -- HOMEOPATA 1, PARTERO 2
    ESTATUS INT, -- INACTIVO 0, ACTIVO 1, SUSPENDIDO 2
	GENERACION VARCHAR(8), -- EJEMPLO 2025-1
    SEDE VARCHAR(50),
    PROMEDIO DECIMAL(4, 2),
    RFC VARCHAR(13) UNIQUE,
    FOREIGN KEY (BOLETA) REFERENCES PERSONA(BOLETA),
    FOREIGN KEY (SEDE) REFERENCES PLAZA(SEDE)
);

CREATE TABLE DIRECCION(
	ALUMNO VARCHAR(12) PRIMARY KEY,
	CALLE VARCHAR(30),
    COLONIA VARCHAR(30),
    CP VARCHAR(5),
    DELEGACION_MUNICIPIO VARCHAR(30),
    ESTADO VARCHAR(30),
    NUM VARCHAR(10),
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA)
);

CREATE TABLE P_ADMIN(
	BOLETA VARCHAR(12) PRIMARY KEY,
	ESTATUS INT, -- INACTIVO 0, ACTIVO 1
    PERFIL INT, -- PRIVILEGIADO 1, NO PRIVILEGIADO 0
    FOREIGN KEY (BOLETA) REFERENCES PERSONA(BOLETA)
);

CREATE TABLE BITACORA(
	ACCION VARCHAR(40),
    BOLETA VARCHAR(12),
    FECHA_EJECUCION DATETIME,
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (BOLETA) REFERENCES PERSONA(BOLETA)
);

CREATE TABLE CODIGO_QR(
    ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12),
    FECHA_LECTURA DATETIME,
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QR VARCHAR(255),  -- MODIFICAR POR EL TIPO DE LIBRERIA A UTILIZAR
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);

CREATE TABLE REPORTE(
    ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12),
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR (255), -- REVISAR ESTE DATO
    EVIDENCIA VARCHAR (50), -- SE COLOCA EL LINK DE LAS CARPETAS DE AMAZON S3 O USAR BLOB
    ESTATUS INT, -- CARGADO 0, EN REVISION 1, FINALIZADO 2 
    FECHA_REGISTRO DATETIME,
    FECHA_MODIFICACION DATETIME,
    FECHA_FINALIZADO DATETIME,
    OBSERVACION VARCHAR (255), 
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);

CREATE TABLE ENCUESTA(
	ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12),
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_REGISTRO DATETIME,
    PREGUNTA INT,
    RESPUESTA INT, -- 1, 2, 3, 4, 5 
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);

CREATE TABLE EXPEDIENTE(
	ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12) PRIMARY KEY,
    ESTATUS INT, --  Sin cargar 1, Pendiente 2, Aprobado 3, Rechazado 4
    FECHA_REGISTRO DATETIME,
    NOMBRE_ARCHIVO VARCHAR(30),
    OBSERVACION VARCHAR(100), 
    RUTA_ARCHIVO VARCHAR(50),
    TIPO INT, -- REGISTRO 1, FINALIZACION 2
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);