CREATE SCHEMA `SISEG` DEFAULT CHARACTER SET utf8 ;

USE SISEG;

create table PERSONA(
    BOLETA VARCHAR(12) PRIMARY KEY, 
    CORREO VARCHAR(50) UNIQUE,
    CURP VARCHAR(18) UNIQUE,
    CONTRASENA VARCHAR(255), -- MODIFICAR POR EL TIPO DE CIFRADO A UTILIZAR
    NOMBRE VARCHAR(30),
    APELLIDO_PATERNO VARCHAR(20),
    APELLIDO_MATERNO VARCHAR(20),
    ROL ENUM('ALUMNO', 'P_ADMIN') NOT NULL, 
    SEXO CHAR(1),
    TELEFONO_MOVIL VARCHAR(10), -- JUNTAR AMBOS TELEFONOS EN UNA COLUMNA ROMPERIA LA NORMALIZACION
    TELEFONO_FIJO VARCHAR(10)
);

CREATE TABLE CARRERA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30)
);

CREATE TABLE ESTATUS_ALUMNO (
    ID INT PRIMARY KEY,
    DESCRIPCION VARCHAR(20)
);

CREATE TABLE ESTATUS_P_ADMIN (
    ID INT PRIMARY KEY,
    DESCRIPCION VARCHAR(20)
);

CREATE TABLE PLAZA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CARRERA INT, -- HOMEOPATA 1, PARTERO 2
    ESTATUS INT, -- INACTIVO 0, ACTIVO 1
	PROMOCION VARCHAR(10), -- EJEMPLO 2025-1
    PROGRAMA VARCHAR(50), -- Se llama programa en el nuevo PDF (PROMOCIÓN DE AGOSTO 2025 – JUNIO  2026)
    SEDE VARCHAR(100), -- Nombre del hospital
    TARJETA_DISPONIBLE INT,
    TIPO_BECA VARCHAR(3), 
    UBICACION VARCHAR(200),
    FOREIGN KEY (CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE ALUMNO(
	BOLETA VARCHAR(12) PRIMARY KEY,
	CARRERA INT, -- HOMEOPATA 1, PARTERO 2
    ESTATUS INT, -- INACTIVO 1, ACTIVO 2, SUSPENDIDO 3
	GENERACION VARCHAR(8), -- EJEMPLO 2025-1
    SEDE INT,
    PROMEDIO DECIMAL(4, 2),
    RFC VARCHAR(13) UNIQUE,
    FOREIGN KEY (BOLETA) REFERENCES PERSONA(BOLETA),
    FOREIGN KEY (SEDE) REFERENCES PLAZA(ID),
    FOREIGN KEY (CARRERA) REFERENCES CARRERA(ID),
    FOREIGN KEY (ESTATUS) REFERENCES ESTATUS_ALUMNO(ID)
);

CREATE TABLE DIRECCION(
	ALUMNO VARCHAR(12) PRIMARY KEY,
	CALLE VARCHAR(30),
    COLONIA VARCHAR(30),
    CP VARCHAR(5),
    DELEGACION_MUNICIPIO VARCHAR(30),
    ESTADO VARCHAR(30),
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA)
);

CREATE TABLE P_ADMIN(
	BOLETA VARCHAR(12) PRIMARY KEY,
	ESTATUS INT, -- INACTIVO 1, ACTIVO 2
    PERFIL INT, -- PRIVILEGIADO 1, NO PRIVILEGIADO 0
    FOREIGN KEY (BOLETA) REFERENCES PERSONA(BOLETA),
    FOREIGN KEY (ESTATUS) REFERENCES ESTATUS_ALUMNO(ID)
);

CREATE TABLE BITACORA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCION VARCHAR(40),
    BOLETA VARCHAR(12),
    FECHA_EJECUCION DATETIME,
    FOREIGN KEY (BOLETA) REFERENCES PERSONA(BOLETA)
);

CREATE TABLE CODIGO_QR(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12),
    FECHA_LECTURA DATETIME,
    QR VARCHAR(255),  -- MODIFICAR POR EL TIPO DE LIBRERIA A UTILIZAR
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);

CREATE TABLE REPORTE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12),
    DESCRIPCION VARCHAR (255), -- REVISAR ESTE DATO
    EVIDENCIA VARCHAR (50), -- SE COLOCA EL LINK DE LAS CARPETAS DE AMAZON S3 O USAR BLOB
    ESTATUS INT, -- CARGADO 0, EN REVISION 1, FINALIZADO 2 
    FECHA_REGISTRO DATETIME,
    FECHA_MODIFICACION DATETIME,
    FECHA_FINALIZADO DATETIME,
    OBSERVACION VARCHAR (255), 
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);

CREATE TABLE ENCUESTA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
	ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12),
    FECHA_REGISTRO DATETIME,
    PREGUNTA INT,
    RESPUESTA INT, -- 1, 2, 3, 4, 5 
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);

CREATE TABLE EXPEDIENTE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ADMIN_ENCARGADO VARCHAR(12),
    ALUMNO VARCHAR(12),
    ESTATUS INT, --  Sin cargar 1, Pendiente 2, Aprobado 3, Rechazado 4
    FECHA_REGISTRO DATETIME,
    NOMBRE_ARCHIVO VARCHAR(30),
    OBSERVACION VARCHAR(100), 
    RUTA_ARCHIVO VARCHAR(50),
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(BOLETA),
    FOREIGN KEY (ADMIN_ENCARGADO) REFERENCES P_ADMIN(BOLETA)
);
