USE SISEG;

-- Catálogo CARRERA
INSERT INTO CARRERA (NOMBRE) VALUES ('MÉDICO CIRJUANO Y HOMEÓPATA');
INSERT INTO CARRERA (NOMBRE) VALUES ('MÉDICO CIRJUANO Y PARTERO');

-- Catálogo ESTATUS_PERSONA
INSERT INTO ESTATUS_ALUMNO (ID, DESCRIPCION) VALUES (0, 'INACTIVO'); 
INSERT INTO ESTATUS_ALUMNO (ID, DESCRIPCION) VALUES (1, 'ACTIVO');
INSERT INTO ESTATUS_ALUMNO (ID, DESCRIPCION) VALUES (2, 'SUSPENDIDO');

-- Catálogo ESTATUS_P_ADMIN
INSERT INTO ESTATUS_P_ADMIN (ID, DESCRIPCION) VALUES (0, 'INACTIVO');
INSERT INTO ESTATUS_P_ADMIN (ID, DESCRIPCION) VALUES (1, 'ACTIVO');

-- Catálogo ESTATUS_QR
INSERT INTO ESTATUS_QR (ID, DESCRIPCION) VALUES (0, 'NO REGISTRADO');
INSERT INTO ESTATUS_QR (ID, DESCRIPCION) VALUES (1, 'REGISTRADO');

-- Catálogo PLAZA MCH
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000266 UMF 3 LA JOYA GUSTAVO A. MADERO', 1, 'A', 'Ote 91, La Joya, Gustavo A. Madero, 07890 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000085 UMF 11 PERALVILLO AZCAPOTZALCO', 2, 'A', 'S/N, Caruso esq, Vallejo, Gustavo A. Madero, 07870 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000650 UMF 16 COL. GUERRERO CUAUHTÉMOC', 3, 'A', 'Francisco, González Bocanegra 10, Guerrero, Cuauhtémoc, 06300 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000254 UMF 23 U. MORELOS GUSTAVO A. MADERO', 4, 'A', 'DFIMS000254 UMF 23 U. MORELOS GUSTAVO A. MADERO');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000341 UMF 35 C.7 ZARAGOZA IZTACALCO', 5, 'A', 'C. 7 200, Agrícola Pantitlán, 08100 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000271 UMF 41 FORTUNA GUSTAVO A. MADERO', 6, 'A', 'Av Fortuna 344, Magdalena de las Salinas, Gustavo A. Madero, 07760 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000295 UMF 94  S JUAN DE ARAGÓN', 7, 'A', 'Calle Camino Antiguo a, Cam. San Juan de Aragón 235, San Juan de Aragón, Gustavo A. Madero, 07950 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000230 HGZMF 29 S. JUAN ARAGÓN GUSTAVO A. MADERO', 8, 'A', 'Av. 510 100, Pueblo de San Juan de Aragón, Gustavo A. Madero, 07950 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000230 HGZMF 29 S. JUAN ARAGÓN GUSTAVO A. MADERO (DONACIÓN DE ORGANOS)', 9, 'A', 'Av. 510 100, Pueblo de San Juan de Aragón, Gustavo A. Madero, 07950 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000213 HT MAGDALENA DE LAS SALINAS GUSTAVO A. MADERO (DONACIÓN DE ORGANOS)', 10, 'A', 'Av Fortuna 101, Magdalena de las Salinas, Gustavo A. Madero, 07760 Ciudad de México, CDMX');

INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS SUR, CDMX', 'DFIMS000580 HES CMN SIGLO XXI UNIDAD DE INVESTIGACIÓN MÉDICA EN INMUNOQUIMICA, UMAE', 21, 'A', 'Av. Cuauhtémoc 330, Doctores, Cuauhtémoc, 06720 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS SUR, CDMX', 'DFIMS000580 HES CMN SIGLO XXI UNIDAD DE INVESTIGACIÓN MÉDICA EN INMUNOQUIMICA, UMAE', 22, 'A', 'Av. Cuauhtémoc 330, Doctores, Cuauhtémoc, 06720 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS SUR, CDMX', 'DFIMS000580 HES CMN SIGLO XXI UNIDAD DE INVESTIGACIÓN MÉDICA EN NEFRÓLOGIA UMAE', 23, 'A', 'Av. Cuauhtémoc 330, Doctores, Cuauhtémoc, 06720 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS SUR, CDMX', 'DFIMS000580 HES CMN SIGLO XXI UNIDAD DE INVESTIGACIÓN MÉDICA EN BIOQUIMICA UMAE', 24, 'A', 'Av. Cuauhtémoc 330, Doctores, Cuauhtémoc, 06720 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (1, 1, '2026-1', 'IMSS SUR, CDMX', 'DFIMS000580 HES CMN SIGLO XXI UNIDAD DE INVESTIGACIÓN MÉDICA EN ENFERMEDADES NEUROLÓGICAS UMAE', 25, 'A', 'Av. Cuauhtémoc 330, Doctores, Cuauhtémoc, 06720 Ciudad de México, CDMX');

-- Catálogo PLAZA MCP
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000756 UMF 5 C. ANAHUAC, MIGUEL HIDALGO', 1, 'A', 'Av. Marina Nacional 5, Popotla, Miguel Hidalgo, 11320 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000085 UMF 11 PERALVILLO AZCAPOTZALCO', 2, 'A', 'S/N, Caruso esq, Vallejo, Gustavo A. Madero, 07870 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000761 UMF 14 AEROPUERTO, VENUSTIANO CARRANZA', 3, 'A', 'Blvd. Puerto Aéreo 88, Santa Cruz Aviación, Venustiano Carranza, 15540 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000242 UMF 20 VALLEJO GUSTAVO A. MADERO', 4, 'A', 'Calz. Vallejo 675, Magdalena de las Salinas, Gustavo A. Madero, 07760 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000254 UMF 23 U. MORELOS GUSTAVO A. MADERO', 5, 'A', 'Eje 5 Nte 516, DM Nacional, Preparatoria 3, Gustavo A. Madero, 07070 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000336 UMF 34 C. PANTITLAN IZTACALCO', 6, 'A', 'S/N entre Calle 2, Av. México 20, Agrícola Pantitlán, Iztacalco, 08100 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000102 UMF 36 C. ATZACOALCO ATZCAPOTZALCO ', 7, 'A', 'Cda. 5 de Mayo S/N, entre Ejido y 5 de mayo, Pueblo de Santiago Atzacoalco, Gustavo A. Madero, 07040 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000283 UMF 44 LA ESCALERA GUSTAVO A. MADERO', 8, 'A', 'Cerrada Plan de San Luis 20, La Purísima Ticoman, Gustavo A. Madero, 07320 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000295 UMF 94  S JUAN DE ARAGÓN', 9, 'A', 'Calle Camino Antiguo a, Cam. San Juan de Aragón 235, San Juan de Aragón, Gustavo A. Madero, 07950 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000230 HGZMF 29 S. JUAN ARAGÓN GUSTAVO A. MADERO', 10, 'A', 'Av. 510 100, Pueblo de San Juan de Aragón, Gustavo A. Madero, 07950 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000230 HGZMF 29 S. JUAN ARAGÓN GUSTAVO A. MADERO', 11, 'A', 'Av. 510 100, Pueblo de San Juan de Aragón, Gustavo A. Madero, 07950 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000831 HGZ NO. 48 SAN PEDRO XALPA AZCAPOTZALCO (DONACIÓN DE ORGANOS)', 12, 'A', 'Elpidio Cortez 300, Santiago Ahuizotla, Azcapotzalco, 02750 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000225 HGZ 24 INSURGENTES GUSTAVO A. MADERO (DONACIÓN DE ORGANOS)', 13, 'A', 'Av. Insurgentes Nte. 1322, Magdalena de las Salinas, Gustavo A. Madero, 07760 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000213 HT MAGDALENA DE LAS SALINAS GUSTAVO A. MADERO (DONACIÓN DE ORGANOS)', 14, 'A', 'Av Fortuna 101, Magdalena de las Salinas, Gustavo A. Madero, 07760 Ciudad de México, CDMX');
INSERT INTO PLAZA (CARRERA, ESTATUS, PROMOCION, PROGRAMA, SEDE, TARJETA_DISPONIBLE, TIPO_BECA, UBICACION) VALUES (2, 1, '2026-1', 'IMSS NORTE, CDMX', 'DFIMS000061 HG CMN LA RAZA (INVESTIGACIÓN)', 15, 'A', 'P.º de las Jacarandas S/N, La Raza, Azcapotzalco, 02990 Ciudad de México, CDMX');